apiVersion: v1
kind: Service
metadata:
  name: {{ include "hbase.fullname" . }}
  labels:
    {{- include "hbase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 60000
      name: hbase-master-api
    - protocol: TCP
      port: 16010
      targetPort: 16010
      name: hbase-master-web-ui
    - protocol: TCP
      port: 60020
      targetPort: 60020
      name: regionserver-api
    - protocol: TCP
      port: 16030
      targetPort: 16030
      name: hbase-regionserver-web-ui
  selector:
    {{- include "hbase.selectorLabels" . | nindent 4 }}