apiVersion: apps/v1
kind: StatefulSet
metadata:
  # name: {{ include "agent.fullname" . }}
  name: pinpoint-agent
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "agent.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "agent.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8079
          envFrom:
          - configMapRef:
              name: pinpoint-config

  