apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 8079
      targetPort: 8079
      name: agent-server-port
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}