apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-config
data:
  ZOO_SERVERS: >-
    pinpoint-zookeeper-0.zoo-zookeeper-headless.pinpoint.svc.cluster.local:2888:3888::1
    pinpoint-zookeeper-1.zoo-zookeeper-headless.pinpoint.svc.cluster.local:2888:3888::2
    pinpoint-zookeeper-2.zoo-zookeeper-headless.pinpoint.svc.cluster.local:2888:3888::3