apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-config
data:
  ZOO_SERVERS: >-
    server.0=pinpoint-zookeeper-0.zoo-zookeeper-headless.pinpoint.svc.cluster.local:2888:3888
    server.1=pinpoint-zookeeper-1.zoo-zookeeper-headless.pinpoint.svc.cluster.local:2888:3888
    server.2=pinpoint-zookeeper-2.zoo-zookeeper-headless.pinpoint.svc.cluster.local:2888:3888