apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "zookeeper.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zookeeper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zookeeper.selectorLabels" . | nindent 8 }}
    spec:
      subdomain: zoo
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: zookeeper
              containerPort: 2181
            - name: zookeeper-election
              containerPort: 2888
            - name: zookeeper-transport
              containerPort: 3888
          env:
          - name: ZOO_MY_ID
            value: {{ index .Values.id (printf "pinpoint-zookeeper-%d" (subtract .Values.replicaCount 1)) }}
          - name: ZOO_SERVERS
            value: server.1=pinpoint-zookeeper-0.pinpoint-zookeeper-headless.pinpoint.svc.cluster.local:2888:3888 server.2=pinpoint-zookeeper-1.pinpoint-zookeeper-headless.pinpoint.svc.cluster.local:2888:3888 server.3=pinpoint-zookeeper-2.pinpoint-zookeeper-headless.pinpoint.svc.cluster.local:2888:3888
          volumeMounts:
            - name: config-volume
              mountPath: /etc/zoo
      # volumes:
      #   - name: config-volume
      #     configMap:
      #       name: zk-config
          