

replicaCount: 1

global:
  storageClass: nfs-client

zookeeper:
  enabled: true
  auth:
    enabled: false
  replicaCout: 1
  image:
    tag: 3.7.0

hbase:
  enabled: true
  image:
    tag: 2.2.7
  hdfs:
    enabled: false

collector:
  replicaCount: 1
  image:
    repository: pinpointdocker/pinpoint-collector
    tag: 2.3.2
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9994

web:
  replicaCount: 1
  image:
    repository: pinpointdocker/pinpoint-web
    tag: 2.3.2
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: pinpoint.local
      paths: ["/"]
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
