apiVersion: v1
kind: Service
metadata:
  name: {{ include "jobmanager.fullname" . }}
  labels:
    {{- include "jobmanager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 6123
      targetPort: 6123
      name: jobmanager
  selector:
    {{- include "jobmanager.selectorLabels" . | nindent 4 }}