apiVersion: apps/v1
kind: StatefulSet
metadata:
  # name: {{ include "jobmanager.fullname" . }}
  name: pinpoint-flink-jobmanager
  labels:
    {{- include "jobmanager.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "jobmanager.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jobmanager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jobmanager.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: pinpoint-flink-jobmanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6123
            - containerPort: 8081
          command:
          - standalone-job 
          - -p 
          - 1 pinpoint-flink-job.jar 
          - -spring.profiles.active release"
          env:
          - name: JOB_MANAGER_RPC_ADDRESS
            value: jobmanager.pinpoint.svc.cluster.local
          - name: PINPOINT_ZOOKEEPER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: pinpoint-config
                key: PINPOINT_ZOOKEEPER_ADDRESS

  