apiVersion: v1
kind: Service
metadata:
  name: {{ include "batch.fullname" . }}
  labels:
    {{- include "batch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 8079
      targetPort: 8079
      name: batch-server-port
  selector:
    {{- include "batch.selectorLabels" . | nindent 4 }}