apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickstart.fullname" . }}
  labels:
    {{- include "quickstart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8080
  selector:
    {{- include "quickstart.selectorLabels" . | nindent 4 }}