apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: web-server-port
    - port: 9997
      targetPort: 9997
      name: thrift-api
  selector:
    {{- include "web.selectorLabels" . | nindent 4 }}