{{- if .Values.collector.enabeld }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pinpoint.fullname" . }}-collector
  labes:
    app: {{ include "pinpoint.name" . }}
    component: collector
spec:
  ports:
  - port: 9994
    targetPort: 9994
  - port: 9995
    targetPort: 9995
  - port: 9996
    targetPort: 9996
  selector:
      app: {{ include "pinpoint.name" . }}
      component: collector
{{- end }}