{{- if .Values.hbase.enabeld }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pinpoint.fullname" . }}-hbase
  labes:
    app: {{ include "pinpoint.name" . }}
    component: hbase
spec:
  ports:
  - port: 16010
    targetPort: 16010
  - port: 16020
    targetPort: 16020
  - port: 16030
    targetPort: 16030
  selector:
      app: {{ include "pinpoint.name" . }}
      component: hbase
{{- end }}