apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pinpoint.fullname" . }}-web
  labes:
    app: {{ include "pinpoint.name" . }}
    component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "pinpoint.name" . }}
      component: web
  template:
    metadata:
      labels: {{ include "pinpoint.name" . }}
      component: web
    spec:
      containers:
      - name: web
        image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        ports:
          - containerPort: 8080
        resources:
{{ toYaml .Values.resource | indent 12 }} 
      nodeSelector: {{ toYaml .Values.nodeSelector | indent 8 }}     
      tolerations: {{ toYaml .Values.tolerations | indent 8 }}     
      affinity: {{ toYaml .Values.affinity | indent 8 }}     

