apiVersion: apps/v1
kind: StatefulSet
metadata:
  # name: {{ include "collector.fullname" . }}
  name: pinpoint-collector
  labels:
    {{- include "collector.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "collector.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "collector.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9991
            - containerPort: 9992
            - containerPort: 9993
            - containerPort: 9994
            - containerPort: 9995
            - containerPort: 9996
          envFrom:
          - configMapRef:
              name: pinpoint-config

  